### PR TITLE
Whitepaper - Update introduction.md (added background)

### PR DESCRIPTION
**Pull request by qwahzi**
Adding background section from the original whitepaper, with some updated stats/sources. Also added some distinguishing factors  of ORV vs traditional PoS

### CODE REVIEW

**Comment by zhyatt** [comment]
@qwahzi Thanks for your continued help with the whitepaper stuff. I merged recent changes from `master` into the `whitepaper` branch due to issues they were causing running your patch. Can you pull those in on your side?

**Comment by qwahzi** [comment]
> @qwahzi Thanks for your continued help with the whitepaper stuff. I merged recent changes from `master` into the `whitepaper` branch due to issues they were causing running your patch. Can you pull those in on your side?

I think I did it, but I'm not sure if I did it correctly. I merged nanocurrency/nano-docs:whitepaper into qwahzi/nano-docs:patch-2 (the branch in this PR). Is that what you were looking for? Or do I need to merge in something else?

**Comment by zhyatt** [comment]
@qwahzi Make sure your master branch is up to date and then from your patch branch do a `git merge master`. You might have a conflict with `mkdocs.yml` file which should be easily resolve by leaving the `master` contents in there and saving. Then doing `git commit` to finish the merge and `git push` to send up. I think that should work.

**Comment by zhyatt** [comment]
@qwahzi Notice there are some conflicts here. I'd like to get #377 merged into `master` before we merge these changes, making the living whitepaper available in WIP form on the site. Once that is done I can help provide feedback on this.

A couple quick notes on formatting stuff as you continue looking into helping here:

- When doing headers we need to keep it to only one instance of H1 (`#`) on the page. H2-H4 headers will still show up in the right nav, H5+ will not.
- For the references in the doc, see how the footnotes are done here: https://docs.nano.org/whitepaper/english/ - this is the preferred setup
- It might be useful to review https://github.com/nanocurrency/nano-docs#nano-protocol-documentation for some tips that can be used for formatting, such as snippets, admonitions, etc. They may come in handy at some point.

And thanks for all your help!

**Comment by qwahzi** [comment]
Sounds good, thanks for the feedback! While waiting for #377, I'll work on updating this PR (patch-2) with the format tips you mentioned

**Comment by zhyatt** [comment]
@qwahzi This got messed up a bit. Can you actually just open a new PR with your changes from `docs/protocol-design/orv-consensus.md` and `docs/protocol-design/introduction.md` copy and pasted over? Sorry for the run around on this, the extra stale branch we were closing out caused some issues.

**Comment by qwahzi** [comment]
> @qwahzi This got messed up a bit. Can you actually just open a new PR with your changes from `docs/protocol-design/orv-consensus.md` and `docs/protocol-design/introduction.md` copy and pasted over? Sorry for the run around on this, the extra stale branch we were closing out caused some issues.

Sure, I can do that!

**Pull request closed without merging**
