### PR TITLE
Update currency units to reflect recent discussions of changes

### PR DESCRIPTION
**Pull request by zhyatt**
Related discussion: https://forum.nano.org/t/discussion-regarding-unit-names/108

### CODE REVIEW

**Comment by Vyryn** [comment]
It's nice to see such a change proposed :)

I recommend against a new official unit for 10^28. This amount is not particularly useful, and the cent/cnano terminology hasn't been used anywhere yet. It also received mixed feelings on the forums. 10^30 and 10^24 are both more useful, and most of the discussion on the forums supported only having in total three official units including 10^0. 10^30 as nano, a 10^24 unit for which the name micronano is fine but not particularly inspired, and a 10^0 unit is all that seems to be required or wanted by the community. The name raw is probably the only one from the original specification that's currently consistently used and clear, so perhaps it shouldn't be changed. The name rai might be very nice for the 10^24 unit, though.

Keeri's post, linked below, summarizes these ideas and appeared to be unanimously liked on the forums. Though there was disagreement above it about the original suggestion, Keeri's proposal appeared to be well liked with no disagreeing posts in the following 9 months.

[](https://forum.nano.org/t/discussion-regarding-unit-names/108/31)

**Comment by cryptocode** [comment]
> This amount is not particularly useful, and the cent/cnano terminology hasn't been used anywhere yet.

I think it'll be useful as Nano moves outside the techie bubble where terms like seed, reps and raw are currently vernacular to the community. Hard to explain, hard to translate.

We wouldn't see nano cents in apps much (if at all), but making it a defined term available for daily speech/writing is useful and aligns with many people's expectations of a day-to-day currency. It's pretty much universally understood that cent means 1/100th of the main denomination. A lot of people are used to cents/pennies, euro cents, peso centavo, lipa, øre in scandinavia, etc. It seems like useful granularity to have even as value fluctuates. _If_ we want to encourage its use, it should also be a well-defined unit.

Just my two nano cents.

**Comment by qwahzi** [comment]
From what I've seen on Reddit/Twitter/Discord, I see a lot of support for 10^24 being Rai vs 10^0 being Rai. Perhaps because it's pretty similar to Bitcoin's Satoshis (sats) named unit, and/or because it remains a precise & useful unit for most of the world even if Nano were to 1000x. Most wallets also show 6 decimal places already, which makes Rai an easy unit to transition to

I personally like "Nano, Cents, Rai, and Raw" as the primary units (and SI units for everything else)

`| Name              | Integer                            | Power    | Previous              |
|-------------------|------------------------------------|----------|-----------------------|
| nano (NANO/Nano)  | 1000000000000000000000000000000    | $10^{30}$| Mnano                 |
| cents (cnano)     | 1000000000000000000000000000       | $10^{28}$| undefined             |
| Rai (μnano) | 1000000000000000000000000          | $10^{24}$| nano (case sensitive) |
| raw               | 1                                  | $10^{0}$ | raw                   |`

**Comment by gak** [comment]
Please keep in mind if you use "micro", it could imply that these are using SI prefixes, so the next level down (10^21) will be `nano-`, i.e. nanonano 😄, then piconano (10^18), etc.

**Comment by cryptocode** [comment]
@gak Yep, SI prefixing is indeed part of the proposal (centi and micro being in the table), see https://forum.nano.org/t/discussion-regarding-unit-names/108
I personally don't see _nanonano_ as an issue, more like a fun quirk of the scheme, and it's not going to come up much in regular use, if at all.

**Comment by otonashixav** [comment]
I'm against the cent as a standardized denomination. We should let it be adopted organically, as there's no way of knowing what the most used denomination of Nano will be -- if in the future 10^24 is the most used denomination, an official cent denomination at 10^28 would only serve to confuse users, much like nano and NANO today.

**Comment by cryptocode** [comment]
@otonashixav 
> We should let it be adopted organically, as there's no way of knowing what the most used denomination of Nano will be

All the SI prefixes are already relative to the base unit, therefore cent(i) will always mean 1/100th of whatever the base denomination is. The exponents are what they are because ^30 is currently the base unit.  If the base unit is ever shifted, so will everything else. I agree there's no need to push centi or any other SI prefix to users, this will work itself out. That said, a lot of people around the world like using a 1/100th unit - where I live we're used to three, cent, eurocent and øre and it works great. Since the proposal is SI prefixes, centi is in there anyway.

**Comment by cryptocode** [comment]
> an official cent denomination at 10^28 would only serve to confuse users

The idea is to have Nano and rai and then SI prefixes for the rest, which means centi is included by definition as well. 

So rather than placing arbitrary SI units in a table, maybe the best way to communicate Nano's unit system is just to define: Nano, rai and point out that base-relative SI prefixes are available for use.

**Comment by nan0nan0** [comment]
there is an integer error here:


cents (cnano) | 1000000000000000000000000000 | $10^{28}$ | undefined

should be 

cents (cnano) | 10000000000000000000000000000 | $10^{28}$ | undefined

**Comment by nan0nan0** [comment]
One idea that I thought was interesting that emerged from discord discussions about this was the idea that you could alter the major Nano denominator as adoption grows. This could be put to a community vote at a specific network threshold, say once there are 20m wallets in daily use.

**Comment by keerifox** [comment]
others on here already mentioned my suggestion, so this is just a reiteration

\-

my proposal is:

| Name 	| Integer 	| Power 	| Previous |
|----------|----------|----------|-----------|
| NANO (case insensitive) | 1000000000000000000000000000000 | $10^{30}$ | Mnano
| rai | 1000000000000000000000000 | $10^{24}$ | nano (case sensitive)
| raw | 1 | $10^{0}$ | raw

> 1 NANO is 1 million rai

in addition to forums, i've also [shared it on reddit](https://www.reddit.com/r/nanocurrency/comments/ljonwz/each_nano_can_be_divided_into_as_much_as_30/gnfr0zi/?context=2) where it was met positively

\-

the unit "raw" is already established and there are no issues with it, it's mostly used by developers and it's good for conveying the smallest unit that can be used. raw = "as is", not formatted

rai is a good word and a little tribute to raiblocks; if need arises, it is short enough to be used in wallet apps in place of word "NANO". meant to be used lowercase, but can be written as Rai or RAI

1/100 is not as useful as 1/millionth, and the issue with using "cent" is that people will _very often_ be confused whether the other person is talking about 1/100 of a US dollar (or sometimes their native currency). this could work if used exactly as "nano cent" and not any other way, but i imagine that would be impossible to enforce – people would likely try using just the word "cents" until they are misunderstood enough times to finally get a habit of adding "nano" in front

**Comment by cryptocode** [comment]
@keerifox 
That brings up a point. The rai unit is a really cool reference that a lot of longtimers like, but for wider adoption that will include people who have not been here since the Raiblocks days, is a "geeky reference" really desirable? Something to take into consideration I think.

I kinda like the idea of _only_ having `NANO` and `raw` in the table, and then have SI units for everything else with proper naming. I'm not sure when people transacting will find 1/millionth useful, but I can see 1/100th having a use, but I might be missing use cases. Using 1/100th shouldn't be confusing if there's proper naming from day one, such as _nanocent_ or _centinano_. That said, I don't think units other than NANO (for people) and raw (mostly for machines) will be used much initially, but SI units are there if needed.

**Comment by qwahzi** [comment]
@cryptocode I think non-geeky people will follow whatever convention the enthusiasts/wallets/services adopt, but a short + simply named common unit will be useful to them as well. Satoshi (sat) is pretty common terminology for Bitcoin these days ("stacking sats"), even though it's also a semi-geeky reference. If Nano ever hits Bitcoin's current market cap, we'd be talking about ~$8000/Nano, and 1 Rai/μnano (10^24; ) would be $0.008 (almost 1 cent USD)

**Comment by cryptocode** [comment]
> and removes the NANO/Nano/nano confusion

@qwahzi  Right, removing confusion is the main goal of course. If we can find easy-to-understand, non-scary terms, then I think those should be picked over geeky ones. When talking to non-tech people about these things, names like seed, raw and representative is _already_ a hurdle, especially when you need to translate them first. Crypto is still adopted mostly by people willing to take that learning curve, which is what I'd like to see lowered, and naming is a very important part of that. It basically can't get simple enough.

**Comment by GeckoFlyingHigh** [comment]
@cryptocode I 100% agree. Lets keep things simple and leave it at Nano and raw only (I'd be happy for raw to be renamed rai).

The name Nano implies it is small. Having 1 Nano worth $100USD isn't particularly useful as a global currency in my opinion. I don't want to count decimal points when making transactions, eg, if someone asks how much is a cheeseburger, I'd prefer to say it's 550 Nano, rather than 0.0005 Nano.

To achieve this, a Nano wouldn't be fixed at 10^30raw, but the integer would be adjusted up or down every 3-5years to bring it in line with the price of certain commodities. One example could be to keep 100 Nano at the global average price of 1L of milk. With the current price of Nano at around $7.50USD and the global price of 1L milk approx. $1.50USD, at this point in time, 1 Nano would need to equate to 10^27raw which would put the global average price of 1L of milk at 200 Nano

Micronano, piconano, nanonano is a no-go imo.

**Comment by nan0nan0** [comment]
I like this idea, as it helps with usability and distribution. I also dislike the idea of having micro, pico etc…

IMO a Commodity Price Index would be a better tool to use than an individual commodity price. Not everyone in the world drinks milk! 

However, this is not a trivial thing. if Nano’s price was volatile and the commodity price was volatile, this could be a nightmare situation if a threshold (±%) was used.

I would like to see an automatic re-denomination vote triggered by set number of blocks, similar to Bitcoin’s halving schedule, which could fall in line to your proposed long term schedule and would avoid arguing over dates. So votes can be cast between Block X - Block Y.

One big issue is that the vote would be non binding and could lead to even more confusion over pricing if exchanges fail to implement re-denomination orders.

BTW I think this thread has outgrown this topic.

**Review by SparK-Cruz — DISMISSED** [review]
I approve of this, even though I think changing raw to rai is as wishful thinking as the current documentation. People use nano and raw, that's it.

**Comment by zhyatt** [comment]
Pushed changes to reflect the general consensus on the thread. Leaving open for additional comments for now.

**Comment by zhyatt** [comment]
Code references to [`mnano`](https://github.com/nanocurrency/nano-node/search?q=mnano) and [`knano`](https://github.com/nanocurrency/nano-node/search?q=knano) will also need review, along with adjustments in QT wallet for `nano` unit.

**Pull request merged**
