### PR TITLE
Update work benchmarks for new kernel performance

### PR DESCRIPTION
**Pull request by zhyatt**

### CODE REVIEW

**Comment by zhyatt** [comment]
@wezrule @SergiySW I had the numbers lined up wrong before, fixed now. Thanks for the callout Serg!

**Comment by zhyatt** [comment]
And now that I think about it more, perhaps the ones we don't have newer numbers for should just be dropped since they were done using the previous kernel. Thoughts?

**Comment by wezrule** [comment]
I think it's fine to remove them, or archive them somewhere else?

**Comment by zhyatt** [comment]
@SergiySW For now I have removed some of the older, less useful values and we can expand in the future.

**Comment by zhyatt** [comment]
@wezrule See comment above, was targeted at you as well :)

**Pull request merged**
