### PR TITLE
Expand the qr standards

### PR DESCRIPTION
**Pull request by Joohansson**
The new nanosign: and nanoprocess: is what's being used in the new remote signing in Nault. I think it can be standardized.

### CODE REVIEW

**Comment by guilhermelawless** [comment]
Great work with this features on Nault @Joohansson ! We definitely want to expand this and make it sufficiently generic to address all use cases we can think of.

Do you think the previous block is necessary when handing off the signed block? Once the block is validated and signed, is there really a need to validate it on the processor side? In that sense, the burden is on the signer to validate it before signing, which requires the previous block.

We're going to look at this from the context of the changes we outlined in https://forum.nano.org/t/work-generation-changes-for-consideration/914 , specifically:
- Direct block handoff option
- Send-receive paired block publishing
- Receive blocks covering send work

**Comment by Joohansson** [comment]
@guilhermelawless You are right, it's not really needed on the processing side but the reason it was included in Nault was to get the same verification screen with the correct amount and transaction subtype (which is derived by comparing balance in previous and new block). But now when I think about it some more, the previous block (and doing the rest of the checks) can actually be requested from the network since we are online in that step anyway. Only downside I can think of is some delay when data is requested and the node is busy. Not a big problem though. I may even refactor that part in Nault making the QR a bit smaller.

**Comment by guilhermelawless** [comment]
Either requested or even cached from before, since you already sent those details to the signer. Thanks!

**Comment by SergiySW** [comment]
I think to comply with standards it would have to use URL encoding of special characters and it would increase block size even more compared to string :(
So we can encode block raw content instead (block type byte and big endian fields as in https://github.com/nanocurrency/nano-node/blob/develop/nano/lib/blocks.cpp#L1142, if don't support legacy types). Here are some approximate calculations for 2 state blocks sum:

- JSON with URL encoding (byte mode): **1286 bytes**
- HEX (byte mode): 872 bytes
- HEX (alphanumeric mode): 601 bytes
- Base32 (byte mode): 701 chars
- Base32 (alphanumeric mode): **482 bytes**
- Base58 (byte mode): 598 chars
- Base64url (byte mode): **584 chars**

For limited set of characters QR code can use alphanumeric mode (5½ bit / character) so Base32 surprisingly is the most effective here. QR code is allowing to mix seperal modes for different code parts so `nanoblock:` or `&previous=` still can be encoded in byte mode while large blocks content in alphanumeric.

I'm not sure if we need separate way for `nanoprocess:` and it can be included in `nanoblock:` instead. Also not sure if we have to include `block=` name field. It will make decoding easier with same field everywhere & then can be even added to `nano:` code (i.e. requesting deposit from user with offline wallet). But result seems a bit awkward to me like
`nanosign:?block=<block content>&previous=<previous block content>`.
URL path can be empty: https://tools.ietf.org/html/rfc3986#section-3.3

**Comment by zhyatt** [comment]
@Joohansson Did you get a chance to see the thoughts from @SergiySW above? We're interested in more of your feedback on this when you are available.

**Comment by Joohansson** [comment]
@zhyatt @SergiySW Ok, so that sounds like a good plan to me. Regarding the encoding format of the QR itself, we may have to take into account what the actual QR libraries can handle. Not all libraries that developer may use have that option I guess. The library that Nault is using for javascript has these settings: https://www.npmjs.com/package/qrcode#encoding-modes

Which means the final size of the QR may increase depending on the library.

nanoprocess: can probably be skipped as previous block is not really needed as Gui pointed out earlier.

"block" and "previous" fields were added to comply with the json format and make it easy to read (for a human) and decode. That can be skipped too if we really want to compress the size. As long as everyone complies with the standard it should be fine. But how do you know if the block is the new block or previous block? By the order as they are defined, like array position 0 and 1?

The nano: format can be used as you say too. But it makes it harder to decode on the frontend QR reader. Right now it detects on the URL protocol (ie. HTTP: | nano: | nanosign: | nanoseed: etc) to know how to encode the rest of the data (for example redirect the wallet to the SEND screen, import seed screen or offline-signing screen). If you include everything under "nano:" then you must check if the block is included or not and act accordingly. You would also make it harder to error check. Like if the block is actually missing by mistake, the wallet will count that as a normal payment request and process it as so, instead of telling the user that the offline signing protocol is bad and the block is actually missing. Therefore, I suggest keeping the offline signing procedure as a separate format. But with the optimizations you suggested.

What is the next step, I'm not sure how to formulate that in my PR. Would be great if I get some kind of counter-proposal in order to modify the PR or something? You know that process better than me.

**Pull request closed without merging**
