### PR TITLE
Add callouts for secure websockets setup

### LINKED ISSUE #587: Document secure WebSocket changes
https://github.com/nanocurrency/nano-node/pull/3032

### PR DESCRIPTION
**Pull request by zhyatt**
Resolves #587

### CODE REVIEW

**Comment by cryptocode** [comment]
With #3032, the [secure] section is gone and replaced with config-tls.toml (some comments about this in the PR)

**Comment by zhyatt** [comment]
> With [nanocurrency/nano-node#3032](https://github.com/nanocurrency/nano-node/pull/3032), the `[secure]` section is gone and replaced with `config-tls.toml`(there are some comments about this in the PR)
> 
> It should also be noted in the docs that, just like the case is with https, wss requires the node to be built with NANO_SECURE_RPC (this should eventually be default IMO, or at least there should be binaries available built with this flag)

Thanks @cryptocode for the review. I added a couple commits which hopefully clarifies this enough. Let me know if anything else needs adjusting.

**Comment by cryptocode** [comment]
@zhyatt I forgot to mention that there's no [secure] section anymore as everything is top-level in the new config file.

Below's a valid `config-tls.toml` example; maybe include it in the docs somewhere?

```toml
enable_https=true
enable_wss=true
verbose_logging=true
server_cert_path="/node/server.cert.pem"
server_key_path="/node/server.key.pem"
server_key_passphrase="test"
server_dh_path="/node/dh1024.pem"
```

**Comment by zhyatt** [comment]
Thanks @cryptocode I missed the variation in configurations and removal of the section. Updated those, perhaps this is well covered now?

**Review by cryptocode — APPROVED** [review]

**Pull request merged**
