### PR TITLE
Logging stable log filename crash

### PR DESCRIPTION
**Pull request by guilhermelawless**
https://github.com/nanocurrency/nano-node/pull/2880

### CODE REVIEW

**Comment by zhyatt** [comment]
@guilhermelawless Can you also add a new snippet for this known issue, maybe pointing back to this spot, and use it in the V21 release snippet here: https://github.com/nanocurrency/nano-docs/blob/master/docs/snippets/release-details-v21-1.md? Other known issues were handled in a similar way.

**Comment by guilhermelawless** [comment]
@zhyatt  thanks, forgot about that! Note the correction as the temporary fix isn't valid because boost log re-creates the `node.log` file when rotating so on restart the user would have to *again* set the properties.

**Comment by zhyatt** [comment]
I added conditionals like:
``` 
{% if page and page.meta.title %}
      <meta name="twitter:title" content="{{ page.meta.title }}">
{% endif %}
```
because the template system was failing due to `page.meta.title` not existing on some pages, seems like it got stricter recently. Now there are generic defaults for these values. Longer term we should add these title/description values on all pages, similar to what is now at the top of the Roadmap page (and a few others).

**Comment by guilhermelawless** [comment]
Thanks for the fix, created an issue to track that. Waiting for approve

**Pull request merged**
