### PR TITLE
Remove trailing whitespaces for each document entry

### PR DESCRIPTION
**Pull request by jserv**
The following command was used:
  find . -iname '*.md' -type f -exec sed -i '' 's/[[:space:]]\{1,\}$//' {} \+

### CODE REVIEW

**Comment by zhyatt** [comment]
@jserv Markdown converts two trailing spaces to a line break and this is sometimes used in the documentation instead of explicit empty lines between paragraphs (note that headers and some other elements include a line break in them, but regular test does not). With this change, it looks like all of that type of line break has been removed, which we don't want to do.

What is the purpose of doing these removals?

**Comment by jserv** [comment]
> What is the purpose of doing these removals?

The intention of removing trailing whitespaces is to minimize the changeset, which is friendly to git apply.
Reference: https://git-scm.com/docs/git-stripspace

**Comment by zhyatt** [comment]
Ok, if we want to get this change made it will need to be done more carefully to avoid formatting changes on the content. If you are able to convert any double-space line endings into full carriage returns perhaps that would work.

@guilhermelawless Do you think the above makes sense? Any other scenarios where spaces are utilized for formatting that you are aware of?

**Comment by guilhermelawless** [comment]
I do like the flexibility of the double-space but being more git-friendly is a good argument against it. @jserv can you provide a command that replaces exactly-double trailing spaces with \n instead? Please run locally using the README instructions to verify the output content does not change. A file with many of these is `commands/command-line-interface.md`

Your command didn't work, any idea?
```bash
(! 2074)->  find . -iname '*.md' -type f -exec sed -i -E '' 's/[[:space:]]{1,}$//' {} +
sed: can't read s/[[:space:]]{1,}$//: No such file or directory
```

**Comment by zhyatt** [comment]
Closing as stale, no response.

**Pull request closed without merging**
